name: TrySomethingDevAmazingPlugin
version: '${version}'
main: net.trysomethingdev.trysomethingdevamazingplugin.TrySomethingDevAmazingPlugin
api-version: '1.20'
commands:
  givechest:
    description: gives a MTM chest to player
    aliases:
      - mtmc
    usage: /<command>
  givefishstation:
   description: gives a fish station to player
   aliases:
     - ftms
   usage: /<command>